### ISSUE TITLE
Add `lenunit` option to `GeoIO.load`

### ISSUE THREAD

**Issue by kramsretlow** [JuliaEarth/GeoIO.jl#100]
I have an .obj file that was exported from a CAD program.  The CAD software was using mm as the unit.  If I import it as a `SimpleMesh` using `GeoIO.load(filename).geometry`, it comes out with units of meters.  Is it (or could it be) possible to specify the units in the call to `load`?  And/or, is there an easy way to change the units of a mesh after creation?  Right now I am using the inelegant way of loading the mesh, then creating a new mesh with a `fix_part_units` function defined like this:

```julia
fix_unit(p) = Meshes.Point((ustrip.([coords(p).x, coords(p).y, coords(p).z]) .* u"mm")...)
fix_part_units(msh) = SimpleMesh([fix_unit(v) for v in vertices(msh)], msh.topology)
```

I've tried searching the docs and source, but I can't find the functionalities I'm after. Sorry if I've missed something.

I'm not familiar with all of the file formats, but I guess this point could apply to some other "unitless" formats as well.

**Comment by juliohm** [comment]
Hi @kramsretlow, it is good to see you.

We should probably add a `lengthunit` option to `load` as suggested given that .obj files don't store units.

Would you like to try adding the option yourself? You can forward it to any affected format, and we can review it.

**Comment by kramsretlow** [comment]
Hi @juliohm , thanks for remembering me 😄

I will try to make some time in the next while to work on it, though I can't promise it'll get done.  So far I was still unable to find the point in the source where the meters unit magically joined my mesh coordinates--will need to check it more deeply.

I'm really enjoying using Meshes.jl for some computation job I'm doing on 3D parts.   If one comes to Meshes.jl from a direction not related to geographical data, it feels slightly odd to need to go to GeoIO.jl (which is clearly geostats related) to load a mesh.   Not a problem, but just a comment from user's perspective.  In any case, thanks for your work on these packages!

**Comment by juliohm** [comment]
> I was still unable to find the point in the source where the meters unit magically joined my mesh coordinates--will need to check it more deeply.

The units are added in the `Point` constructor. You can write `Point(x, y)` with `x` and `y` unitful quantities:

```julia
Point(1mm, 2mm)
```

`m` is the default unit when `x` and `y` are not unitful.

You can add a unit to a pre-existing tuple with:

```julia
u = mm

Point(x * u, y * u)
```

> I'm really enjoying using Meshes.jl for some computation job I'm doing on 3D parts.

Glad you are enjoying it :) 

> If one comes to Meshes.jl from a direction not related to geographical data, it feels slightly odd to need to go to GeoIO.jl (which is clearly geostats related) to load a mesh. Not a problem, but just a comment from user's perspective. In any case, thanks for your work on these packages!

GeoIO.jl is not tied to GeoStats.jl (the package), but is certainly related to GeoStats.jl (the framework). It doesn't depend on the "stats" part of "geostats". Think of it as a simple tool to load geospatial data as geotables, which can be used for any purpose beyond geospatial data science and geostatistical modeling.

**Comment by juliohm** [comment]
@kramsretlow the option should be available now. Please update the environment.

I will leave the issue open because there some other formats also support the option, but we didn't have time to implement yet:

- [ ] vtk
- [ ] img
- [ ] csv

**Comment by mobley-trent** [comment]
Hello @juliohm correct me if I'm wrong but this issue seems to have been fixed in #110

**Comment by juliohm** [comment]
@mobley-trent it is partially fixed. The option is not available in the formats listed above in a check list.

**Comment by mobley-trent** [comment]
I see that `vtkread`, `imgread` and `csvread` are defined in the `load` function. Perhaps I am missing something @juliohm ?

**Comment by juliohm** [comment]
Fixed for all backends.
