### ISSUE TITLE
Read GeoTiff with adequate projection and numeric values

### ISSUE THREAD

**Issue by ErickChacon** [JuliaEarth/GeoIO.jl#46]
Currently `.tif` files which contain spatial coordinates with respect to a CRS are being read as an image losing information about he coordinates and also the values do not need to be colors. We can fix it by reading the file with `ArchGDAL.jl` and make the conversion to `Meshes.jl`.

**Comment by juliohm** [comment]
Thank you @ErickChacon , I think we can use TiffImages.jl directly to read geotiff in pure Julia.

Related: https://github.com/tlnagy/TiffImages.jl/issues/100

**Comment by ErickChacon** [comment]
Interesting! I already have a code using `ArchGDAL.jl`. However it might be interesting to set it up using `TiffImages.jl` and just include it inside `GeoIO.jl`?

**Comment by juliohm** [comment]
@eliascarv just finished a code using ArchGDAL.jl as a workaround until TiffImages.jl supports geotiff metadata. We should be reviewing a PR this afternoon (BRT).

**Comment by ErickChacon** [comment]
Sounds good!
