### ISSUE TITLE
GeoTable from NaturalEarth has wrong unit

### ISSUE THREAD

**Issue by disberd** [JuliaEarth/GeoIO.jl#94]
Hello,

I just realized that the table coming out of the output from NaturalEarth (example https://github.com/JuliaEarth/GeoArtifacts.jl#naturalearth in the Readme) creates a domain whose points are expressed in `m`, despite having the values which are corresponding to longitude and latitude in degrees.

![image](https://github.com/JuliaEarth/GeoArtifacts.jl/assets/12846528/9a73352f-08aa-4e25-a56d-95b4b9bfd671)

I understand this as that is the default unit to the new Point type, but the input data from the NaturalEarth repository is in latitude/longitude in degrees so at first glance this might seem misleading.

Is this something intended or should it be fixed or made more explicit in the documentation?
~~Is it alternatively possible to create the geometries directly using `LatLon` from CoordRefSystems?~~
I just realized that you can use LatLon to generate a Point, but this would need some modification in the functions in GeoIO to specify how to handle LatLon when converting from GeoJSON.FeatureCollection to:
![image](https://github.com/JuliaEarth/GeoArtifacts.jl/assets/12846528/f22c358b-e9ab-4936-bf62-cb3e68719d1c)

**Comment by juliohm** [comment]
I've transferred the issue to GeoIO.jl. PRs are welcome that fix specific loaders.

**Comment by juliohm** [comment]
Closing it in favor of #87
